language: node_js
node_js:
  - "9"
dist: trusty
services:
  - mongodb
addons:
  sonarcloud:
    organization: "spoiled-tomatillos" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token
env:
  - NODE_ENV=test PORT=3000
cache:
  directories:
    - node_modules
    - frontend/node_modules
#install:
#  - npm install
#  - npm run build

jobs:
  include:
    - stage: install
      script:
        - npm install
        - npm run build
    - stage: test
      script:
        - nohup npm run start &
        - sleep 3
        - npm run test
    - stage: sonarCloud
      script:
        - npm run nyc
        - sonar-scanner
    - stage: quality
      script:
        - npm run SonarCloudCheck
